### PR TITLE
add new template function signature which returns []byte

### PR DESCRIPTION
**Pull request by shkim**
I use ECHO web framework ( https://echo.labstack.com )
and I also got tired of repeating the same boilerplate over and over:

```
buffer := new(bytes.Buffer)
template.SomeFunc(..., buffer)
return echoCtx.HTMLBlob(http.StatusOK, buffer.Bytes())
```
So I added another template function type to easily use with ECHO web framework, like this:

```
return echoCtx.HTMLBlob(http.StatusOK, template.SomeFunc(...))
```

### CODE REVIEW

**Comment by shiyanhui** [comment]
`[]byte` may be modified when the same buffer object is reused in buffer pool. That's why Hero haven't support `return-[]byte` functions like `func f(x, y...) []byte` yet.

The problem is that you can't use both buffer pool and `return-[]byte` functions elegantly.

Go to https://github.com/golang/go/blob/master/src/bytes/buffer.go#L47 for more information.

**Comment by shkim** [comment]
Is it significant performance down to use **new(bytes.Buffer)** rather than _hero.GetBuffer()_ for every template buffer generation?
In ECHO framework, using directly http.ResponseWriter (io.Writer) is not trivial for users.

**Comment by shiyanhui** [comment]
The less temporary objects, the less press to GC, and surely the better performance. Hero do can support `return-[]byte` without buffer pool if you don't care the performance.

**Comment by shkim** [comment]
Is it already implemented feature?: `return-[]byte`
I didn't see howto in documentation.

I think I can ignore the performance gap because the ECHO framework currently allocates new buffer for every template rendering.

FYI, https://github.com/labstack/echo/blob/master/context.go#L368

**Comment by shiyanhui** [comment]
Not yet. I will add this feature as soon as possible :)

**Comment by shkim** [comment]
Thanks, I'll use my patch until the official hero update comes :)

**Pull request closed without merging**
